<?php 
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_5400deaeebc9c',
	'title' => 'Home Content',
	'fields' => array (
		array (
			'key' => 'field_5400e3bdc9eb8',
			'label' => 'Student Videos',
			'name' => 'student_videos',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '1',
			'max' => '3',
			'layout' => 'table',
			'button_label' => 'Add Student',
			'sub_fields' => array (
				array (
					'key' => 'field_5400e2e5c9eb4',
					'label' => 'Student Name',
					'name' => 'student_name',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5400e302c9eb5',
					'label' => 'Student Country',
					'name' => 'student_country',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5400e383c9eb7',
					'label' => 'Student Country Flag',
					'name' => 'student_country_flag',
					'prefix' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_5400e346c9eb6',
					'label' => 'Student Image',
					'name' => 'student_image',
					'prefix' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array (
					'key' => 'field_5404ed0c14095',
					'label' => 'Student Video',
					'name' => 'student_video',
					'prefix' => '',
					'type' => 'file',
					'instructions' => 'Select the video to display for this student',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'return_format' => 'array',
					'library' => 'all',
				),
			),
		),
		array (
			'key' => 'field_540122549db7a',
			'label' => 'Banner Text',
			'name' => 'esl_banner_text',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_540546d111f9a',
			'label' => 'Banner Link',
			'name' => 'esl_banner_link',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Enter an absolute or relative link',
			'required' => 1,
			'conditional_logic' => 0,
			'default_value' => '/',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5400e3eec9eba',
			'label' => 'Content Boxes',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_5400e3fec9ebb',
			'label' => 'Content Box',
			'name' => 'esl_content_box',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Content Box',
			'sub_fields' => array (
				array (
					'key' => 'field_5400e411c9ebc',
					'label' => 'Box Content',
					'name' => 'esl_box_content',
					'prefix' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 1,
					'tabs' => 'all',
				),
			),
		),
		array (
			'key' => 'field_5400e823b3871',
			'label' => 'Home Content',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_5400e833b3872',
			'label' => 'Home Content',
			'name' => 'esl_home_content',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 1,
			'tabs' => 'all',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'site-options',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'tags',
		6 => 'send-trackbacks',
	),
));

endif;
?>