<?php 
/*
Feature Name:   ACF Fields: Site Information
Description:    Make it is to keep the company or site details in one place to use throughout theme development
Dependencies:   ACF
*/

if( function_exists('register_field_group') ):

register_field_group(array (
        'key' => 'group_540652e7b47b9',
        'title' => 'Site Information',
        'fields' => array (
                array (
                        'key' => 'field_5406561db1958',
                        'label' => 'Company Details',
                        'name' => '',
                        'prefix' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                ),
                array (
                        'key' => 'field_5406530bb1951',
                        'label' => 'Brand Name',
                        'name' => 'brand_name',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'The full company/business or brand name <strong style="float:right;">(ACF: brand_name)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'Brand or Company Name',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065673b195b',
                        'label' => 'Email',
                        'name' => 'email',
                        'prefix' => '',
                        'type' => 'email',
                        'instructions' => 'Enter the email to be publicly displayed <strong style="float:right;">(ACF: email)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'admin@mycompany.com',
                        'prepend' => '',
                        'append' => '',
                ),
                array (
                        'key' => 'field_540653a7b1952',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Enter the main phone number <strong style="float:right;">(ACF: phone)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => '123.456.7890',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 20,
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_5406542bb1953',
                        'label' => 'Alt Phone',
                        'name' => 'alt_phone',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Enter the alternative phone number <strong style="float:right;">(ACF: alt_phone)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => '987.654.3210',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 20,
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_540654a3b1954',
                        'label' => 'Street Address',
                        'name' => 'street_address',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Enter the street address of the place or business <strong style="float:right;">(ACF: street_address)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => '777 N. Calvary Rd',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065509b1955',
                        'label' => 'City',
                        'name' => 'city',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Enter the city of the place or business <strong style="float:right;">(ACF: city)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'Los Angeles',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_540655ccb1956',
                        'label' => 'State',
                        'name' => 'state',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Enter the state of the place or business <strong style="float:right;">(ACF: state)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'CA',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_540655eab1957',
                        'label' => 'Zip Code',
                        'name' => 'zip_code',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Enter the zip code of the place or business <strong style="float:right;">(ACF: zip_code)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 90210,
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065642b1959',
                        'label' => 'Social Media',
                        'name' => '',
                        'prefix' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                ),
                array (
                        'key' => 'field_54065659b195a',
                        'label' => 'Facebook',
                        'name' => 'facebook',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Facebook page here <strong style="float:right;">(ACF: facebook)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'http://facebook.com/my-page',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065716b195c',
                        'label' => 'Flicker',
                        'name' => 'flicker',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Flickr page here <strong style="float:right;">(ACF: flicker)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'https://www.flickr.com/photos/username/',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_540657d4b195d',
                        'label' => 'Goodreads',
                        'name' => 'goodreads',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Goodreads page here <strong style="float:right;">(ACF: goodreads)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'http://www.goodreads.com/author/show/username',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065876b195e',
                        'label' => 'Google Plus',
                        'name' => 'google_plus',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Google+ page here <strong style="float:right;">(ACF: google_plus)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'https://plus.google.com/u/0/your-user-id-here/posts',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_540658d0b195f',
                        'label' => 'Instagram',
                        'name' => 'instagram',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Instagram page here <strong style="float:right;">(ACF: instagram)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'http://instagram.com/username',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_5406594fb1960',
                        'label' => 'LinkedIn',
                        'name' => 'linkedin',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the LinkedIn page here <strong style="float:right;">(ACF: linkedin)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'https://www.linkedin.com/profile/view?id=user-id',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_540659a9b1961',
                        'label' => 'Pinterest',
                        'name' => 'pinterest',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Pinterest page here <strong style="float:right;">(ACF: pinterest)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'http://www.pinterest.com/username/',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065a16b1962',
                        'label' => 'Twitter',
                        'name' => 'twitter',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the Twitter page here <strong style="float:right;">(ACF: twitter)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'http://twitter.com/username',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_54065a39b1963',
                        'label' => 'YouTube',
                        'name' => 'youtube',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add the YouTube page here <strong style="float:right;">(ACF: youtube)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'https://www.youtube.com/user/username',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
                array (
                        'key' => 'field_eh9813wg87wetr',
                        'label' => 'Analytics',
                        'name' => '',
                        'prefix' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                ),
                array (
                        'key' => 'field_987gh198732',
                        'label' => 'Google Analytics',
                        'name' => 'google_analytics',
                        'prefix' => '',
                        'type' => 'textarea',
                        'instructions' => 'Insert the google analytics tracking code to be used on the site <strong style="float:right;">(ACF: google_analytics)</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => '<script>
  (function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,"script","//www.google-analytics.com/analytics.js","ga");

  ga("create", "UA-XXXXXXXX-X":, "auto");
  ga("send", "pageview");

</script>',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                ),
        ),
        'location' => array (
                array (
                        array (
                                'param' => 'options_page',
                                'operator' => '==',
                                'value' => 'site-info',
                        ),
                ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
));

endif;
?>